### ISSUE TITLE
Feature request: support other etherscan-like services

### ISSUE THREAD

**Issue by mo-rijndael** [BerzanXYZ/escan#1]
Such as bscscan, or others. Looks like they all have same API, so we just need to add ability to choose base url

**Comment by berzanorg** [comment]
Hey! Thank you for your request. I've modified almost all the files and changed the names of a few functions, and escan now supports Binance Smart Chain. If you want to contribute and add support for other Etherscan-like services you are welcome.

**Comment by berzanorg** [comment]
Or you can tell me the others that you know, so I can add support for them.
