### ISSUE TITLE
Max Priority Fee on transaction 

### ISSUE THREAD

**Issue by rshuwy** [BerzanXYZ/escan#2]
Hello Sir, 

Thx for this, can you please add the max priority fee and max fee per gas on the transaction struct. 

Thankyou.

**Comment by berzanorg** [comment]
Hi!
Firstly, I am really sorry I haven't had a chance to check the issues of this repo.
Secondly, this crate is only a wrapper around Etherscan's API.
I'm not sure if Etherscan's API gives a response that contains max priority fee.

https://docs.etherscan.io/api-endpoints/accounts#get-internal-transactions-by-transaction-hash
